### ISSUE TITLE
Google apps not working on android phones

### ISSUE THREAD

**Issue by amarkudov** [divestedcg/dnsrm#3]
I'm using divblock on DivestedWRT. Blocking is good but i have trouble with android phones on my network. Google apps(Translate, Keep, Maps) and Rakuten Viber(chat works, cant send photos/videos) on android phones does not seem to work. Can't find the right domains to add in the exclusion list. Tried adding all the domains from dnsrm repo to exclusion list still no luck.

**Comment by SkewedZeppelin** [comment]
It purposely allows hundreds of Google domains and is unlikely to block them.

I use Google Translate and Maps myself along with websites like search and have no issue.

> Tried adding all the domains from dnsrm repo to exclusion list still no luck.

The generated list is already checked against the exclusion list here, you can see which entries were removed: https://divested.dev/hosts-removed

Please use an app like [PCAPDroid](https://f-droid.org/en/packages/com.emanuelef.remote_capture/) on your phone or use this command on your OpenWrt device: `tcpdump -i br-lan udp port 53`

**Comment by amarkudov** [comment]
When i activate PCAPDroid I get two errors on HTTPS 443, translate-pa.googleapis.com and clients1.google.com but apps work. As soon as I disable PCAPDroid everything stops working. 
I noticed that when I'm connected over VPN(Wireguard) to my network i don't have any problems. I was thinking maybe its not the divblock but when i disable it in OpenWrt everything works as it should. 
I have tested on 3 different devices and i get the same behavior.

**Comment by SkewedZeppelin** [comment]
ah
try commenting the `interface=br-lan` line in /etc/dnsmasq.conf and rebooting

**Comment by amarkudov** [comment]
Nothing has changed, the problem still exists.

**Comment by SkewedZeppelin** [comment]
Are you using any other local proxy or custom DNS?

**Comment by amarkudov** [comment]
No, I'm not using local proxy or custom DNS.

**Comment by SkewedZeppelin** [comment]
You can entirely rule out divblock using `/etc/init.d/divblock disable` and reboot

The domains you listed are not blocked.

**Comment by amarkudov** [comment]
Got it working, had to add traffic rule in firewall for br-lan on port 53. Thank you for the support and your time.
