### ISSUE TITLE
mydealz.de

### ISSUE THREAD

**Issue by Kelvino9** [divestedcg/dnsrm#6]
If possible please add following URLs to the exclusion list so the mydealz.de App or at least the website can be opened when the host list is activated.

App:
www.mydealz.de
static.mydealz.de
assets.mydealz.de

Website:
www.mydealz.de
static.mydealz.de
ocular.mydealz.de

**Comment by SkewedZeppelin** [comment]
These domains are not included

**Comment by SkewedZeppelin** [comment]
Fixed in next update, thank you for reporting.

**Comment by Kelvino9** [comment]
Thank you!
